### ISSUE TITLE
Error when starting world

### ISSUE THREAD

**Issue by sweetsosweet** [joshiejack/CopyPaste#1]
I get a crash when I try to open a world or start a new world.

[Link](http://pastebin.com/4ApxivJZ)

Edit: The error goes away after I create the config/copy folder manually. 

Edit again: using copypaste-1.0.jar in 1.10.2

**Comment by joshiejack** [comment]
Yeah, the folder isn't automatically created. I figured people would do that before loading it up anyway. Is it really worth it to generate it?

**Comment by sweetsosweet** [comment]
Well, if it didn't crash your game, it wouldn't matter. But the fact that it crashed after everything was loaded and only after I loaded a world was kind of annoying. It won't happen again now that I've created the folder, but not everyone will think to create the folder first thing.

Edit: Actually, you could just mention that we should create the folder first in the description, that would help.

**Comment by GirafiStudios** [comment]
README is added on Github now. Information about the need to create the config/copy folder yourself is already on CurseForge.
