### ISSUE TITLE
Crash - IllegalArgumentException: Parameter 'directory' is not a directory

### ISSUE THREAD

**Issue by ProsperCraft** [joshiejack/CopyPaste#4]
Crash report- https://gist.github.com/ProsperCraft/62a1753261f30e774d566d3b409ba024

Debug log- 
https://gist.github.com/ProsperCraft/6a1000b80e3b2f16885ca372f2d3e579

copypaste-1.3

**Comment by GirafiStudios** [comment]
Thank you for the report!
I'll look into fixing it asap.

**Comment by GirafiStudios** [comment]
Did you remember to create the copy folder in /config yourself?
