### ISSUE TITLE
copypaste.jar failed to load a valid ResourcePackInfo

### ISSUE THREAD

**Issue by kil0byt3** [joshiejack/CopyPaste#5]
New to 1.14 modding, wading my way into modpack creation. Copypaste gives me this on startup, yet works fine. Any fix?
[latest.log](https://github.com/joshiejack/CopyPaste/files/4447544/latest.log)

![image](https://user-images.githubusercontent.com/39413400/78730912-02f1ab80-78f3-11ea-8350-9a00d685b92d.png)

**Comment by GirafiStudios** [comment]
Fixed by https://github.com/joshiejack/CopyPaste/commit/8215d72b10fa36f0bc6369b516091e17760a58f5
New build will be available shortly.
