### ISSUE TITLE
Crash when creating a new world while the config/copy folder is missing

### ISSUE THREAD

**Issue by TheDeviantCrafter** [joshiejack/CopyPaste#6]
Crash report: https://pastebin.com/Mc4J6Czb

The easiest solution is probably to automatically generate a copy folder on startup. If the user deletes the copy folder after the pack starts up, the mod should simply do nothing instead of crashing.

**Comment by GirafiStudios** [comment]
The folder is automatically generated in CopyPaste 1.4.
The user have to manually create the folder for older versions.
